import * as cdk from 'aws-cdk-lib';
import * as s3 from 'aws-cdk-lib/aws-s3';
import * as secretsmanager from 'aws-cdk-lib/aws-secretsmanager';
import type { Construct } from 'constructs';

import type { EnvironmentConfig } from '../types.js';

export interface CloudflareBootstrapStackProps extends cdk.StackProps {
  readonly config: EnvironmentConfig;
}

/**
 * AWS-side bootstrap for the Cloudflare edge migration (task 0277 / ADR 0048),
 * so nothing is created by hand. Gated by `config.provisionCloudflareBootstrap`
 * and deployed FIRST (before `terraform apply` and before the CloudFront
 * secret-header lock is populated).
 *
 * Creates:
 *  - the Terraform remote-state S3 bucket (versioned, encrypted, private,
 *    enforced-TLS, RETAIN) — the backend for `infra/cloudflare/`
 *  - the `X-Origin-Secret` in Secrets Manager with a CDK-generated value
 *    (alphanumeric, no whitespace/newline) — read by the Terraform Transform
 *    Rule and copied into the CloudFront KeyValueStore by the operator
 *
 * NOT here (external credential / crypto — cannot be IaC-generated):
 *  - the Cloudflare API token → paste once via `aws secretsmanager
 *    put-secret-value` (it comes from the Cloudflare dashboard)
 *  - the mTLS client cert/key → operator `openssl` (see infra/cloudflare/certs/)
 */
export class CloudflareBootstrapStack extends cdk.Stack {
  constructor(
    scope: Construct,
    id: string,
    props: CloudflareBootstrapStackProps
  ) {
    super(scope, id, props);

    const { config } = props;

    // Terraform remote-state backend bucket. Holds the origin secret + mTLS
    // key as state attributes, so it must stay private + encrypted + versioned
    // (see infra/cloudflare/secrets.tf + README). RETAIN — never auto-delete
    // state.
    const tfStateBucket = new s3.Bucket(this, 'CloudflareTfState', {
      bucketName: `${config.envName}-soroban-explorer-cf-tfstate`,
      versioned: true,
      blockPublicAccess: s3.BlockPublicAccess.BLOCK_ALL,
      // SSE-KMS, UNCONDITIONALLY — not gated on config.kmsEncryption (that flag
      // is the auto-delete/cost knob: it drives autoDeleteObjects elsewhere).
      // This bucket holds SECRETS at rest (origin secret + mTLS client key as
      // Terraform state attributes) regardless of that knob, so it always
      // warrants KMS — unlike the public on-chain XDR in the ledger bucket
      // (SSE-S3, task 0278). The operator's profile needs S3 write here; the
      // aws/s3 managed key permits KMS via the S3 service, so `encrypt = true`
      // in backend.hcl works without an extra key grant.
      encryption: s3.BucketEncryption.KMS_MANAGED,
      enforceSSL: true,
      removalPolicy: cdk.RemovalPolicy.RETAIN,
    });

    // X-Origin-Secret — value generated by CDK. Alphanumeric only
    // (excludePunctuation + no includeSpace) so it is header-safe and never
    // contains whitespace/newline. RETAIN so rotation is deliberate, not a
    // teardown side effect.
    const originSecret = new secretsmanager.Secret(this, 'OriginSecret', {
      secretName: `soroban/${config.envName}/cloudflare/origin-secret`,
      description:
        'X-Origin-Secret shared by the Cloudflare Transform Rule and the CloudFront viewer-request Function (task 0277 / ADR 0048).',
      removalPolicy: cdk.RemovalPolicy.RETAIN,
      generateSecretString: {
        passwordLength: 48,
        excludePunctuation: true,
      },
    });

    cdk.Tags.of(this).add('Project', 'soroban-block-explorer');
    cdk.Tags.of(this).add('Environment', config.envName);
    cdk.Tags.of(this).add('ManagedBy', 'cdk');

    // Bucket name → backend.hcl. Secret ARN/name → reference only (value never
    // output).
    new cdk.CfnOutput(this, 'CloudflareTfStateBucketName', {
      value: tfStateBucket.bucketName,
    });
    new cdk.CfnOutput(this, 'OriginSecretName', {
      value: originSecret.secretName,
    });
  }
}
