#!/usr/bin/env bash
#
# Issue an mTLS client certificate signed by the team-owned CA.
#
# Usage:
#   ./issue-client-cert.sh <CN> [--force]
#
# Arguments:
#   <CN>     Common Name for the certificate. Conventionally:
#              - dev laptops:    <firstname>-laptop      (e.g. alice-laptop)
#              - AWS services:   <service>-<env>         (e.g. lambda-api-prod)
#              - CI runners:     ci-<purpose>            (e.g. ci-smoke)
#
#   --force  Overwrite an existing output directory. WITHOUT this
#            flag the script refuses to clobber a previously issued
#            certificate — explicit opt-in protects against an
#            accidental rotation that invalidates a deployed cert.
#
# Inputs:
#   The CA private key is read from a tmpfs path. The operator
#   fetches it from the password manager into /dev/shm/soroban-ca/ca.key
#   right before running this script, and shreds it right after.
#
#   To override the location, set CA_KEY_PATH in the environment.
#
# Outputs:
#   ./out/<CN>/<CN>.crt   Signed client certificate
#   ./out/<CN>/<CN>.key   Client private key (chmod 0600)
#   ./out/<CN>/ca.crt     Copy of the CA certificate for convenience
#                         (clients usually need both files)
#
# Notes:
#   - The client key is generated locally and never leaves the
#     operator's machine via this script. Transferring it to a
#     consumer (AWS Secrets Manager, dev laptop) is a separate
#     deliberate step documented in README.md.
#   - The certificate carries `clientAuth` EKU only — it cannot be
#     used as a server certificate even if leaked.

set -euo pipefail

# ---------------------------------------------------------------------
# Arguments & configuration
# ---------------------------------------------------------------------

if [[ $# -lt 1 ]]; then
    echo "Usage: $0 <CN> [--force]" >&2
    exit 64
fi

readonly CN="$1"
FORCE=0
if [[ "${2:-}" == "--force" ]]; then
    FORCE=1
fi

# Refuse obvious garbage in the CN early. CN goes into the cert
# Subject and into audit logs — restrict to a safe character set.
if [[ ! "${CN}" =~ ^[a-zA-Z0-9._-]+$ ]]; then
    echo "ERROR: CN '${CN}' contains characters outside [a-zA-Z0-9._-]." >&2
    echo "       Stick to lowercase alphanumerics plus '.', '_', '-'." >&2
    exit 64
fi

readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly CA_CRT="${SCRIPT_DIR}/ca.crt"
readonly CA_KEY_PATH="${CA_KEY_PATH:-/dev/shm/soroban-ca/ca.key}"
readonly OUT_DIR="${SCRIPT_DIR}/out/${CN}"

readonly CERT_DAYS=365  # Annual rotation; documented in README.md

# ---------------------------------------------------------------------
# Pre-flight
# ---------------------------------------------------------------------

if ! command -v openssl >/dev/null 2>&1; then
    echo "ERROR: openssl not found on PATH." >&2
    exit 1
fi

if [[ ! -f "${CA_CRT}" ]]; then
    echo "ERROR: CA certificate ${CA_CRT} not found." >&2
    echo "       Run generate-ca.sh first (or git pull if it was generated by a teammate)." >&2
    exit 1
fi

if [[ ! -f "${CA_KEY_PATH}" ]]; then
    echo "ERROR: CA private key ${CA_KEY_PATH} not found." >&2
    echo "       Fetch it from the password manager entry 'soroban-prod / ca-key' into" >&2
    echo "       ${CA_KEY_PATH} (tmpfs), then re-run this script." >&2
    exit 1
fi

# Mode on the CA key must be tight — refuse to use it if anyone
# but the owner can read. Catches the case where the operator
# accidentally drops it into a world-readable directory.
#
# Portable across GNU coreutils (`stat -c '%a'`) and BSD stat
# on macOS (`stat -f '%OLp'`). `%OLp` formats the lower-9 bits
# (file permissions only, no type bits) as octal. We accept
# both 3-digit and 4-digit-with-leading-zero variants because
# different stat builds emit either.
if CA_KEY_MODE="$(stat -c '%a' "${CA_KEY_PATH}" 2>/dev/null)"; then
    :
elif CA_KEY_MODE="$(stat -f '%OLp' "${CA_KEY_PATH}" 2>/dev/null)"; then
    :
else
    echo "ERROR: neither GNU nor BSD stat could read ${CA_KEY_PATH} mode." >&2
    exit 1
fi
readonly CA_KEY_MODE

case "${CA_KEY_MODE}" in
    600|400|0600|0400) : ;;
    *)
        echo "ERROR: ${CA_KEY_PATH} has mode ${CA_KEY_MODE}; expected 600 or 400." >&2
        echo "       Tighten permissions before continuing: chmod 600 ${CA_KEY_PATH}" >&2
        exit 1
        ;;
esac

if [[ -d "${OUT_DIR}" && ${FORCE} -eq 0 ]]; then
    echo "ERROR: ${OUT_DIR} already exists." >&2
    echo "       A certificate for CN='${CN}' has been issued before." >&2
    echo "       To rotate intentionally, re-run with --force; the old files will be overwritten." >&2
    exit 1
fi

# ---------------------------------------------------------------------
# Cleanup on failure — never leave half-written artefacts behind.
# ---------------------------------------------------------------------

WORK_DIR=""
cleanup() {
    local rc=$?
    if [[ -n "${WORK_DIR}" && -d "${WORK_DIR}" ]]; then
        rm -rf "${WORK_DIR}"
    fi
    if [[ $rc -ne 0 && -d "${OUT_DIR}" && ${FORCE} -eq 0 ]]; then
        # If we created OUT_DIR this run and then failed, wipe it
        # so a retry sees a clean state. Skip on --force where the
        # directory existed before.
        rm -rf "${OUT_DIR}"
    fi
}
trap cleanup EXIT

# ---------------------------------------------------------------------
# Issue
# ---------------------------------------------------------------------

WORK_DIR="$(mktemp -d -p /dev/shm "issue-${CN}.XXXXXX")"
install -d -m 0700 "${OUT_DIR}"

readonly CLIENT_KEY="${OUT_DIR}/${CN}.key"
readonly CLIENT_CRT="${OUT_DIR}/${CN}.crt"
readonly CLIENT_CSR="${WORK_DIR}/${CN}.csr"

echo "==> Generating client private key (ECDSA P-256)"
openssl genpkey \
    -algorithm EC \
    -pkeyopt ec_paramgen_curve:P-256 \
    -out "${CLIENT_KEY}"
chmod 0600 "${CLIENT_KEY}"

echo "==> Generating certificate signing request"
openssl req \
    -new \
    -key "${CLIENT_KEY}" \
    -out "${CLIENT_CSR}" \
    -subj "/CN=${CN}"

# Random 128-bit serial. Earlier versions of this script used
# `-CAcreateserial` with a tmpfs-local ca.srl, which meant every
# issued cert ended up with serial 0x01 — a CA/B-Forum-illegal
# collision that also breaks audit-by-serial. A fresh
# cryptographically-random serial per issuance has effectively
# zero collision probability and needs no state on disk.
#
# The leading nibble is masked to ≤7 so the DER encoding stays
# unambiguously positive across openssl 1.1 and 3.x.
SERIAL_HEX="$(openssl rand -hex 16)"
SERIAL_HIGH_BYTE="$(( 0x${SERIAL_HEX:0:2} & 0x7F ))"
readonly SERIAL="0x$(printf '%02x' "${SERIAL_HIGH_BYTE}")${SERIAL_HEX:2}"

# The signed certificate carries clientAuth EKU only. Caddy's
# `client_auth.mode require_and_verify` validates the chain against
# our CA; downstream audit logs read CN from the Subject.
echo "==> Signing certificate (valid ${CERT_DAYS} days, serial ${SERIAL})"
openssl x509 \
    -req \
    -in "${CLIENT_CSR}" \
    -CA "${CA_CRT}" \
    -CAkey "${CA_KEY_PATH}" \
    -set_serial "${SERIAL}" \
    -out "${CLIENT_CRT}" \
    -days "${CERT_DAYS}" \
    -extfile <(cat <<EOF
basicConstraints = critical,CA:FALSE
keyUsage = critical,digitalSignature,keyEncipherment
extendedKeyUsage = clientAuth
subjectKeyIdentifier = hash
authorityKeyIdentifier = keyid,issuer
EOF
)
chmod 0644 "${CLIENT_CRT}"

# Drop the CA cert next to the client material for convenience.
cp "${CA_CRT}" "${OUT_DIR}/ca.crt"

# ---------------------------------------------------------------------
# Operator hand-off
# ---------------------------------------------------------------------

cat <<EOF

============================================================
Client certificate issued.

  CN:        ${CN}
  Cert:      ${CLIENT_CRT}
  Key:       ${CLIENT_KEY}
  CA cert:   ${OUT_DIR}/ca.crt
  Valid for: ${CERT_DAYS} days

  Fingerprint:
$(openssl x509 -in "${CLIENT_CRT}" -noout -fingerprint -sha256 | sed 's/^/    /')

NEXT STEPS — depending on the consumer:

  Dev laptop:
    cp ${CLIENT_CRT} ~/.certs/${CN}.crt
    cp ${CLIENT_KEY} ~/.certs/${CN}.key
    chmod 600 ~/.certs/${CN}.key
    # Also store both files in your password manager as a backup.

  AWS service (Lambda / Galexie):
    Assemble a JSON bundle and upload to AWS Secrets Manager.
    See infra-hetzner/ca/README.md "Issuing AWS service certs"
    for the exact aws-cli invocation.

When you are done, REMEMBER to:
  - shred the CA key from /dev/shm if you fetched it for this run
  - decide whether ${OUT_DIR} should be kept (e.g. dev laptops keep
    a local copy) or shredded (e.g. AWS service certs that now
    live solely in Secrets Manager).
============================================================
EOF
